services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "3003:3003"
    environment:
      - ALLOWED_ORIGINS
      - NODE_ENV=production
    restart: always
