version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "8888:8888"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  backend:
    build:
      context: ./backend
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/app
